import { DistributionMetadata } from '../../types/rarity';

export const WORLD_POPULATION_ESTIMATE = 8_100_000_000;

export const DISTRIBUTIONS: Record<string, DistributionMetadata> = {
  birthDecade: {
    attribute: 'birthDecade',
    label: 'Birth Cohort',
    prevalence: {
      '2005_plus': 0.31,
      '1995_2004': 0.16,
      '1985_1994': 0.15,
      '1975_1984': 0.13,
      '1965_1974': 0.11,
      'pre_1965': 0.14,
    },
    source: 'Global Demographic Cohort Estimate (UN Population Division Reference Model)',
    year: 2024,
    population: 'Global population (~8.1B)',
    geography: 'Global',
    methodology: 'Age-bracket demographic aggregation',
    confidence: 'high',
    isDemoEstimate: false,
  },
  birthMonth: {
    attribute: 'birthMonth',
    label: 'Birth Month',
    prevalence: {
      jan: 0.083,
      feb: 0.077,
      mar: 0.084,
      apr: 0.081,
      may: 0.083,
      jun: 0.082,
      jul: 0.086,
      aug: 0.088,
      sep: 0.090,
      oct: 0.085,
      nov: 0.080,
      dec: 0.081,
    },
    source: 'Global Seasonal Natality Distribution Estimate',
    year: 2024,
    population: 'Global live births reference',
    geography: 'Global',
    methodology: 'Monthly birth frequency weighted by hemisphere seasonality',
    confidence: 'high',
    isDemoEstimate: false,
  },
  birthRegion: {
    attribute: 'birthRegion',
    label: 'Region of Birth',
    prevalence: {
      east_se_asia: 0.285,
      south_asia: 0.248,
      sub_saharan_africa: 0.155,
      europe: 0.092,
      latin_america: 0.082,
      mena: 0.065,
      north_america: 0.047,
      oceania: 0.006,
    },
    source: 'Macro-Regional Population Share Estimate',
    year: 2024,
    population: 'Global population (~8.1B)',
    geography: 'Global',
    methodology: 'Macro-geographic demographic distribution',
    confidence: 'high',
    isDemoEstimate: false,
  },
  handedness: {
    attribute: 'handedness',
    label: 'Dominant Hand',
    prevalence: {
      right: 0.888,
      left: 0.101,
      ambidextrous: 0.011,
    },
    source: 'Broad Meta-Analysis of Human Handedness Prevalence (Estimate)',
    year: 2024,
    population: 'General human population',
    geography: 'Global',
    methodology: 'Cross-cultural motor preference synthesis',
    confidence: 'high',
    isDemoEstimate: false,
  },
  siblings: {
    attribute: 'siblings',
    label: 'Sibling Count',
    prevalence: {
      none: 0.16,
      one: 0.31,
      two: 0.25,
      three: 0.15,
      four_plus: 0.13,
    },
    source: 'Global Household & Fertility Composition Estimate (Prototype Model)',
    year: 2024,
    population: 'Adult & adolescent population',
    geography: 'Global',
    methodology: 'Estimated household parity distribution',
    confidence: 'medium',
    isDemoEstimate: true,
  },
  heightRange: {
    attribute: 'heightRange',
    label: 'Adult Height Bracket',
    prevalence: {
      under_160: 0.24,
      '160_169': 0.36,
      '170_179': 0.27,
      '180_189': 0.11,
      '190_plus': 0.02,
    },
    source: 'Global Adult Stature Distribution Estimate (Pooled Sex Reference)',
    year: 2024,
    population: 'Global adult population',
    geography: 'Global',
    methodology: 'Normal distribution approximation across pooled stature ranges',
    confidence: 'medium',
    isDemoEstimate: true,
  },
  chronotype: {
    attribute: 'chronotype',
    label: 'Circadian Preference',
    prevalence: {
      early_bird: 0.18,
      morning_lean: 0.26,
      intermediate: 0.32,
      night_owl: 0.18,
      extreme_owl: 0.06,
    },
    source: 'Chronobiology Sleep-Wake Preference Estimate (Prototype Model)',
    year: 2024,
    population: 'General population',
    geography: 'Global',
    methodology: 'Self-reported circadian preference distribution estimate',
    confidence: 'medium',
    isDemoEstimate: true,
  },
  petPreference: {
    attribute: 'petPreference',
    label: 'Companion Animal Preference',
    prevalence: {
      dogs: 0.39,
      cats: 0.23,
      both: 0.24,
      neither: 0.14,
    },
    source: 'Cross-National Companion Animal Affinity Estimate (Prototype Model)',
    year: 2024,
    population: 'General population',
    geography: 'Global',
    methodology: 'Survey synthesis of stated animal preference',
    confidence: 'low',
    isDemoEstimate: true,
  },
  languages: {
    attribute: 'languages',
    label: 'Conversational Languages',
    prevalence: {
      one: 0.40,
      two: 0.43,
      three: 0.13,
      four_plus: 0.04,
    },
    source: 'Global Linguistic Repertoire & Multilingualism Estimate',
    year: 2024,
    population: 'Global population',
    geography: 'Global',
    methodology: 'Estimated conversational proficiency across primary and secondary tongues',
    confidence: 'medium',
    isDemoEstimate: true,
  },
  coffeeHabit: {
    attribute: 'coffeeHabit',
    label: 'Caffeine & Coffee Ritual',
    prevalence: {
      daily_multi: 0.28,
      daily_one: 0.22,
      occasional: 0.18,
      tea_only: 0.21,
      none: 0.11,
    },
    source: 'Global Beverage Consumption Pattern Estimate (Prototype Model)',
    year: 2024,
    population: 'Adult & young adult population',
    geography: 'Global',
    methodology: 'Habitual beverage preference estimate',
    confidence: 'low',
    isDemoEstimate: true,
  },
  socialEnergy: {
    attribute: 'socialEnergy',
    label: 'Evening Social Preference',
    prevalence: {
      stay_in_always: 0.22,
      stay_in_mostly: 0.34,
      balanced: 0.26,
      go_out_mostly: 0.13,
      go_out_always: 0.05,
    },
    source: 'Behavioral Leisure & Social Recharge Estimate (Prototype Model)',
    year: 2024,
    population: 'General population',
    geography: 'Global',
    methodology: 'Self-reported leisure preference model',
    confidence: 'low',
    isDemoEstimate: true,
  },
  sleepTime: {
    attribute: 'sleepTime',
    label: 'Typical Sleep Onset',
    prevalence: {
      before_10pm: 0.14,
      '10pm_midnight': 0.48,
      'midnight_2am': 0.29,
      after_2am: 0.09,
    },
    source: 'Habitual Bedtime Distribution Estimate (Prototype Model)',
    year: 2024,
    population: 'General population',
    geography: 'Global',
    methodology: 'Estimated sleep onset timing',
    confidence: 'low',
    isDemoEstimate: true,
  },

  // Bonus / Upgrade attributes ("CAN YOU GET RARER?")
  eyeColor: {
    attribute: 'eyeColor',
    label: 'Eye Pigmentation',
    prevalence: {
      brown: 0.78,
      blue: 0.09,
      hazel: 0.05,
      amber: 0.05,
      green: 0.02,
      gray: 0.01,
    },
    source: 'Global Ocular Melanin & Iris Phenotype Estimate',
    year: 2024,
    population: 'Global population',
    geography: 'Global',
    methodology: 'Phenotypic frequency approximation across global populations',
    confidence: 'medium',
    isDemoEstimate: false,
  },
  cilantro: {
    attribute: 'cilantro',
    label: 'Cilantro (OR6A2) Perception',
    prevalence: {
      herbal: 0.68,
      soap: 0.12,
      neutral: 0.14,
      never_tried: 0.06,
    },
    source: 'Olfactory Receptor Sensory Variation Estimate (Prototype Model)',
    year: 2024,
    population: 'General population',
    geography: 'Global',
    methodology: 'Estimated prevalence of soapy aldehyde detection vs preference',
    confidence: 'medium',
    isDemoEstimate: true,
  },
  tongueRoll: {
    attribute: 'tongueRoll',
    label: 'Tongue Rolling Motor Trait',
    prevalence: {
      yes: 0.69,
      no: 0.28,
      cloverleaf: 0.03,
    },
    source: 'Classical Human Motor Trait Frequency Estimate',
    year: 2024,
    population: 'General population',
    geography: 'Global',
    methodology: 'Phenotypic survey approximation',
    confidence: 'medium',
    isDemoEstimate: true,
  },
  livedAbroad: {
    attribute: 'livedAbroad',
    label: 'International Residence',
    prevalence: {
      never: 0.86,
      under_1yr: 0.07,
      one_country: 0.05,
      two_plus: 0.02,
    },
    source: 'Global Cross-Border Mobility & Migration Estimate',
    year: 2024,
    population: 'Global population',
    geography: 'Global',
    methodology: 'Estimated share of population living outside birth country',
    confidence: 'medium',
    isDemoEstimate: true,
  },
  seasonPreference: {
    attribute: 'seasonPreference',
    label: 'Preferred Season',
    prevalence: {
      spring: 0.28,
      summer: 0.29,
      autumn: 0.29,
      winter: 0.14,
    },
    source: 'Seasonal Preference Survey Estimate (Prototype Model)',
    year: 2024,
    population: 'General population',
    geography: 'Global',
    methodology: 'Aggregated seasonal preference polling approximation',
    confidence: 'low',
    isDemoEstimate: true,
  },
  driversLicense: {
    attribute: 'driversLicense',
    label: 'Driver Licensing Status',
    prevalence: {
      yes_regular: 0.36,
      yes_rarely: 0.12,
      no_license: 0.52,
    },
    source: 'Global Motorist & Licensing Penetration Estimate',
    year: 2024,
    population: 'Global population',
    geography: 'Global',
    methodology: 'Estimated licensed drivers relative to global population',
    confidence: 'medium',
    isDemoEstimate: true,
  },
};

export interface CorrelationRule {
  id: string;
  primaryQuestionId: string;
  primaryOptions: string[];
  dependentQuestionId: string;
  dependentOptions: string[];
  conditionalProbabilityMultiplier: number; // > 1 means dependent option is MORE likely given primary option, dampening artificial rarity
  explanation: string;
}

/**
 * Explicit correlation adjustments so the rarity engine does not blindly assume
 * full statistical independence across obviously linked traits.
 */
export const CORRELATION_RULES: CorrelationRule[] = [
  {
    id: 'chronotype_sleep_late',
    primaryQuestionId: 'chronotype',
    primaryOptions: ['night_owl', 'extreme_owl'],
    dependentQuestionId: 'sleepTime',
    dependentOptions: ['midnight_2am', 'after_2am'],
    conditionalProbabilityMultiplier: 2.15,
    explanation: 'Night owls are substantially more likely to sleep after midnight; adjusted to avoid double-counting late sleep habits.',
  },
  {
    id: 'chronotype_sleep_early',
    primaryQuestionId: 'chronotype',
    primaryOptions: ['early_bird', 'morning_lean'],
    dependentQuestionId: 'sleepTime',
    dependentOptions: ['before_10pm', '10pm_midnight'],
    conditionalProbabilityMultiplier: 1.45,
    explanation: 'Morning-oriented individuals more frequently sleep before midnight; adjusted for circadian correlation.',
  },
  {
    id: 'region_tea_culture',
    primaryQuestionId: 'birthRegion',
    primaryOptions: ['east_se_asia', 'south_asia'],
    dependentQuestionId: 'coffeeHabit',
    dependentOptions: ['tea_only'],
    conditionalProbabilityMultiplier: 1.65,
    explanation: 'Tea preference has higher baseline prevalence across South, East, and Southeast Asia.',
  },
  {
    id: 'region_multilingual_high',
    primaryQuestionId: 'birthRegion',
    primaryOptions: ['europe', 'south_asia', 'sub_saharan_africa'],
    dependentQuestionId: 'languages',
    dependentOptions: ['two', 'three', 'four_plus'],
    conditionalProbabilityMultiplier: 1.4,
    explanation: 'Multilingualism has higher regional density in Europe, South Asia, and Sub-Saharan Africa.',
  },
  {
    id: 'region_monolingual_anglo',
    primaryQuestionId: 'birthRegion',
    primaryOptions: ['north_america', 'oceania'],
    dependentQuestionId: 'languages',
    dependentOptions: ['one'],
    conditionalProbabilityMultiplier: 1.55,
    explanation: 'Monolingualism is more statistically common in North America and Oceania.',
  },
  {
    id: 'region_eye_color_europe',
    primaryQuestionId: 'birthRegion',
    primaryOptions: ['europe', 'north_america', 'oceania'],
    dependentQuestionId: 'eyeColor',
    dependentOptions: ['blue', 'green', 'hazel', 'gray'],
    conditionalProbabilityMultiplier: 2.6,
    explanation: 'Lighter iris phenotypes occur at higher rates in European-descended populations.',
  },
  {
    id: 'social_late_sleep',
    primaryQuestionId: 'socialEnergy',
    primaryOptions: ['go_out_mostly', 'go_out_always'],
    dependentQuestionId: 'sleepTime',
    dependentOptions: ['midnight_2am', 'after_2am'],
    conditionalProbabilityMultiplier: 1.35,
    explanation: 'Frequent evening socializers tend to have later bedtimes.',
  },
  {
    id: 'age_drivers_license',
    primaryQuestionId: 'birthDecade',
    primaryOptions: ['2005_plus'],
    dependentQuestionId: 'driversLicense',
    dependentOptions: ['no_license'],
    conditionalProbabilityMultiplier: 1.4,
    explanation: 'Younger cohorts have a higher proportion of non-licensed individuals.',
  },
];
