import { Question } from '../../types/quiz';

export const CORE_QUESTIONS: Question[] = [
  {
    id: 'birthDecade',
    tier: 'core',
    numberLabel: '01',
    prompt: 'Which period were you born in?',
    subtitle: 'Broad cohorts help estimate demographic patterns without needing your exact birthday.',
    category: 'demographics',
    options: [
      { id: '2005_plus', label: '2005 or later', shortTag: 'BORN 2005+', cardLabel: 'Born 2005 or later' },
      { id: '1995_2004', label: '1995 – 2004', shortTag: '1995–2004 COHORT', cardLabel: 'Born 1995–2004' },
      { id: '1985_1994', label: '1985 – 1994', shortTag: '1985–1994 COHORT', cardLabel: 'Born 1985–1994' },
      { id: '1975_1984', label: '1975 – 1984', shortTag: '1975–1984 COHORT', cardLabel: 'Born 1975–1984' },
      { id: '1965_1974', label: '1965 – 1974', shortTag: '1965–1974 COHORT', cardLabel: 'Born 1965–1974' },
      { id: 'pre_1965', label: 'Before 1965', shortTag: 'PRE-1965 COHORT', cardLabel: 'Born before 1965' },
    ],
  },
  {
    id: 'birthMonth',
    tier: 'core',
    numberLabel: '02',
    prompt: 'What month were you born?',
    category: 'demographics',
    options: [
      { id: 'jan', label: 'January', shortTag: 'JANUARY', cardLabel: 'Born in January' },
      { id: 'feb', label: 'February', shortTag: 'FEBRUARY', cardLabel: 'Born in February' },
      { id: 'mar', label: 'March', shortTag: 'MARCH', cardLabel: 'Born in March' },
      { id: 'apr', label: 'April', shortTag: 'APRIL', cardLabel: 'Born in April' },
      { id: 'may', label: 'May', shortTag: 'MAY', cardLabel: 'Born in May' },
      { id: 'jun', label: 'June', shortTag: 'JUNE', cardLabel: 'Born in June' },
      { id: 'jul', label: 'July', shortTag: 'JULY', cardLabel: 'Born in July' },
      { id: 'aug', label: 'August', shortTag: 'AUGUST', cardLabel: 'Born in August' },
      { id: 'sep', label: 'September', shortTag: 'SEPTEMBER', cardLabel: 'Born in September' },
      { id: 'oct', label: 'October', shortTag: 'OCTOBER', cardLabel: 'Born in October' },
      { id: 'nov', label: 'November', shortTag: 'NOVEMBER', cardLabel: 'Born in November' },
      { id: 'dec', label: 'December', shortTag: 'DECEMBER', cardLabel: 'Born in December' },
    ],
  },
  {
    id: 'birthRegion',
    tier: 'core',
    numberLabel: '03',
    prompt: 'Which part of the world were you born in?',
    category: 'demographics',
    options: [
      { id: 'east_se_asia', label: 'East or Southeast Asia', shortTag: 'EAST/SE ASIA', cardLabel: 'From East/SE Asia' },
      { id: 'south_asia', label: 'South Asia', shortTag: 'SOUTH ASIA', cardLabel: 'From South Asia' },
      { id: 'europe', label: 'Europe', shortTag: 'EUROPE', cardLabel: 'From Europe' },
      { id: 'north_america', label: 'North America', shortTag: 'NORTH AMERICA', cardLabel: 'From North America' },
      { id: 'latin_america', label: 'Latin America or Caribbean', shortTag: 'LATIN AMERICA', cardLabel: 'From Latin America' },
      { id: 'sub_saharan_africa', label: 'Sub-Saharan Africa', shortTag: 'SUB-SAHARAN AFRICA', cardLabel: 'From Sub-Saharan Africa' },
      { id: 'mena', label: 'Middle East or North Africa', shortTag: 'MENA REGION', cardLabel: 'From MENA region' },
      { id: 'oceania', label: 'Oceania', shortTag: 'OCEANIA', cardLabel: 'From Oceania' },
    ],
  },
  {
    id: 'handedness',
    tier: 'core',
    numberLabel: '04',
    prompt: 'Which hand do you naturally write with?',
    category: 'biology',
    options: [
      { id: 'right', label: 'Right-handed', shortTag: 'RIGHT-HANDED', cardLabel: 'Right-handed' },
      { id: 'left', label: 'Left-handed', shortTag: 'LEFT-HANDED', cardLabel: 'Left-handed' },
      { id: 'ambidextrous', label: 'Ambidextrous (Both equally)', shortTag: 'AMBIDEXTROUS', cardLabel: 'Ambidextrous' },
    ],
  },
  {
    id: 'siblings',
    tier: 'core',
    numberLabel: '05',
    prompt: 'How many siblings do you have?',
    category: 'demographics',
    options: [
      { id: 'none', label: 'None (Only child)', shortTag: 'ONLY CHILD', cardLabel: 'Only child' },
      { id: 'one', label: '1 sibling', shortTag: '1 SIBLING', cardLabel: '1 sibling' },
      { id: 'two', label: '2 siblings', shortTag: '2 SIBLINGS', cardLabel: '2 siblings' },
      { id: 'three', label: '3 siblings', shortTag: '3 SIBLINGS', cardLabel: '3 siblings' },
      { id: 'four_plus', label: '4 or more', shortTag: '4+ SIBLINGS', cardLabel: '4+ siblings' },
    ],
  },
  {
    id: 'heightRange',
    tier: 'core',
    numberLabel: '06',
    prompt: 'Approximately how tall are you?',
    category: 'biology',
    options: [
      { id: 'under_160', label: 'Under 160 cm', subtext: 'Under 5′3″', shortTag: 'UNDER 160CM', cardLabel: 'Under 160 cm tall' },
      { id: '160_169', label: '160 – 169 cm', subtext: '5′3″ – 5′6″', shortTag: '160–169CM', cardLabel: '160–169 cm tall' },
      { id: '170_179', label: '170 – 179 cm', subtext: '5′7″ – 5′10″', shortTag: '170–179CM', cardLabel: '170–179 cm tall' },
      { id: '180_189', label: '180 – 189 cm', subtext: '5′11″ – 6′2″', shortTag: '180–189CM', cardLabel: '180–189 cm tall' },
      { id: '190_plus', label: '190 cm or taller', subtext: '6′3″ or taller', shortTag: '190CM+ TALL', cardLabel: '190 cm+ tall' },
    ],
  },
  {
    id: 'chronotype',
    tier: 'core',
    numberLabel: '07',
    prompt: 'Are you more of a morning person or a night person?',
    category: 'chronobiology',
    options: [
      { id: 'early_bird', label: 'Definite morning person', shortTag: 'EARLY BIRD', cardLabel: 'Early bird' },
      { id: 'morning_lean', label: 'Mostly morning', shortTag: 'MORNING LEAN', cardLabel: 'Morning person' },
      { id: 'intermediate', label: 'Somewhere in the middle', shortTag: 'ADAPTABLE CLOCK', cardLabel: 'Mid-day chronotype' },
      { id: 'night_owl', label: 'Night owl', shortTag: 'NIGHT OWL', cardLabel: 'Night owl' },
      { id: 'extreme_owl', label: 'Extreme night owl', shortTag: 'EXTREME NIGHT OWL', cardLabel: 'Extreme night owl' },
    ],
  },
  {
    id: 'petPreference',
    tier: 'core',
    numberLabel: '08',
    prompt: 'Do you prefer cats, dogs, both, or neither?',
    category: 'behavior',
    options: [
      { id: 'dogs', label: 'Dogs', shortTag: 'DOG PERSON', cardLabel: 'Prefers dogs' },
      { id: 'cats', label: 'Cats', shortTag: 'CAT PERSON', cardLabel: 'Prefers cats' },
      { id: 'both', label: 'Both equally', shortTag: 'CATS & DOGS', cardLabel: 'Likes cats & dogs' },
      { id: 'neither', label: 'Neither', shortTag: 'NO PETS', cardLabel: 'Prefers neither pet' },
    ],
  },
  {
    id: 'languages',
    tier: 'core',
    numberLabel: '09',
    prompt: 'How many languages can you hold a conversation in?',
    category: 'culture',
    options: [
      { id: 'one', label: 'One language', shortTag: 'MONOLINGUAL', cardLabel: 'Speaks 1 language' },
      { id: 'two', label: 'Two languages', shortTag: 'BILINGUAL', cardLabel: 'Bilingual' },
      { id: 'three', label: 'Three languages', shortTag: 'TRILINGUAL', cardLabel: 'Trilingual' },
      { id: 'four_plus', label: 'Four or more', shortTag: 'POLYGLOT (4+)', cardLabel: 'Speaks 4+ languages' },
    ],
  },
  {
    id: 'coffeeHabit',
    tier: 'core',
    numberLabel: '10',
    prompt: 'Do you drink coffee?',
    category: 'behavior',
    options: [
      { id: 'daily_multi', label: 'Multiple cups every day', shortTag: 'HEAVY COFFEE', cardLabel: 'Multi-cup coffee drinker' },
      { id: 'daily_one', label: 'One cup a day', shortTag: 'DAILY COFFEE', cardLabel: 'Daily coffee drinker' },
      { id: 'occasional', label: 'Occasionally', shortTag: 'OCCASIONAL COFFEE', cardLabel: 'Occasional coffee' },
      { id: 'tea_only', label: 'No, I prefer tea', shortTag: 'TEA DEVOTEE', cardLabel: 'Tea over coffee' },
      { id: 'none', label: 'No caffeine at all', shortTag: 'CAFFEINE-FREE', cardLabel: 'Caffeine-free' },
    ],
  },
  {
    id: 'socialEnergy',
    tier: 'core',
    numberLabel: '11',
    prompt: 'Do you prefer staying in or going out?',
    category: 'behavior',
    options: [
      { id: 'stay_in_always', label: 'Almost always staying in', shortTag: 'HOMEBODY', cardLabel: 'Dedicated homebody' },
      { id: 'stay_in_mostly', label: 'Usually staying in', shortTag: 'QUIET EVENINGS', cardLabel: 'Prefers staying in' },
      { id: 'balanced', label: 'Equal mix of both', shortTag: 'AMBIVERT PACE', cardLabel: 'Balanced social energy' },
      { id: 'go_out_mostly', label: 'Usually going out', shortTag: 'OUTBOUND SOCIAL', cardLabel: 'Prefers going out' },
      { id: 'go_out_always', label: 'Always out whenever possible', shortTag: 'NIGHTLIFE REGULAR', cardLabel: 'Always going out' },
    ],
  },
  {
    id: 'sleepTime',
    tier: 'core',
    numberLabel: '12',
    prompt: 'When do you usually go to sleep?',
    category: 'chronobiology',
    options: [
      { id: 'before_10pm', label: 'Before 10:00 PM', shortTag: 'SLEEPS <10PM', cardLabel: 'Sleeps before 10 PM' },
      { id: '10pm_midnight', label: 'Between 10:00 PM and Midnight', shortTag: '10PM–12AM SLEEP', cardLabel: 'Sleeps 10 PM–Midnight' },
      { id: 'midnight_2am', label: 'Between Midnight and 2:00 AM', shortTag: 'PAST MIDNIGHT', cardLabel: 'Sleeps past midnight' },
      { id: 'after_2am', label: 'After 2:00 AM', shortTag: 'SLEEPS 2AM+', cardLabel: 'Sleeps after 2 AM' },
    ],
  },
];

export const BONUS_QUESTIONS: Question[] = [
  {
    id: 'eyeColor',
    tier: 'bonus',
    numberLabel: 'B1',
    prompt: 'What color are your eyes?',
    category: 'biology',
    options: [
      { id: 'brown', label: 'Brown', shortTag: 'BROWN EYES', cardLabel: 'Brown eyes' },
      { id: 'blue', label: 'Blue', shortTag: 'BLUE EYES', cardLabel: 'Blue eyes' },
      { id: 'hazel', label: 'Hazel', shortTag: 'HAZEL EYES', cardLabel: 'Hazel eyes' },
      { id: 'amber', label: 'Amber', shortTag: 'AMBER EYES', cardLabel: 'Amber eyes' },
      { id: 'green', label: 'Green', shortTag: 'GREEN EYES', cardLabel: 'Green eyes' },
      { id: 'gray', label: 'Gray', shortTag: 'GRAY EYES', cardLabel: 'Gray eyes' },
    ],
  },
  {
    id: 'cilantro',
    tier: 'bonus',
    numberLabel: 'B2',
    prompt: 'How does cilantro (coriander leaf) taste to you?',
    category: 'biology',
    options: [
      { id: 'herbal', label: 'Fresh and citrusy', shortTag: 'LIKES CILANTRO', cardLabel: 'Enjoys cilantro' },
      { id: 'soap', label: 'It tastes like soap', shortTag: 'CILANTRO = SOAP', cardLabel: 'Cilantro tastes like soap' },
      { id: 'neutral', label: 'Neutral / barely notice it', shortTag: 'CILANTRO NEUTRAL', cardLabel: 'Cilantro neutral' },
      { id: 'never_tried', label: 'Not sure / never tried it', shortTag: 'NO CILANTRO DATA', cardLabel: 'Unfamiliar with cilantro' },
    ],
  },
  {
    id: 'tongueRoll',
    tier: 'bonus',
    numberLabel: 'B3',
    prompt: 'Can you roll your tongue into a tube?',
    category: 'biology',
    options: [
      { id: 'yes', label: 'Yes, easily', shortTag: 'TONGUE ROLLER', cardLabel: 'Can roll tongue' },
      { id: 'no', label: 'No, not at all', shortTag: 'NON-ROLLER', cardLabel: 'Cannot roll tongue' },
      { id: 'cloverleaf', label: 'I can fold a cloverleaf shape', shortTag: 'CLOVERLEAF TONGUE', cardLabel: 'Cloverleaf tongue folder' },
    ],
  },
  {
    id: 'livedAbroad',
    tier: 'bonus',
    numberLabel: 'B4',
    prompt: 'Have you lived in a country other than where you were born?',
    category: 'culture',
    options: [
      { id: 'never', label: 'No, never', shortTag: 'DOMESTIC ROOTS', cardLabel: 'Lived in birth country' },
      { id: 'under_1yr', label: 'Yes, for less than a year', shortTag: 'BRIEF EXPAT', cardLabel: 'Lived abroad <1 year' },
      { id: 'one_country', label: 'Yes, in one other country', shortTag: '2-COUNTRY LIFE', cardLabel: 'Lived in 2 countries' },
      { id: 'two_plus', label: 'Yes, in two or more other countries', shortTag: 'GLOBAL NOMAD', cardLabel: 'Lived in 3+ countries' },
    ],
  },
  {
    id: 'seasonPreference',
    tier: 'bonus',
    numberLabel: 'B5',
    prompt: 'Which season do you prefer most?',
    category: 'behavior',
    options: [
      { id: 'spring', label: 'Spring', shortTag: 'SPRING PERSON', cardLabel: 'Prefers spring' },
      { id: 'summer', label: 'Summer', shortTag: 'SUMMER PERSON', cardLabel: 'Prefers summer' },
      { id: 'autumn', label: 'Autumn / Fall', shortTag: 'AUTUMN PERSON', cardLabel: 'Prefers autumn' },
      { id: 'winter', label: 'Winter', shortTag: 'WINTER PERSON', cardLabel: 'Prefers winter' },
    ],
  },
  {
    id: 'driversLicense',
    tier: 'bonus',
    numberLabel: 'B6',
    prompt: 'Do you have a driver’s license?',
    category: 'culture',
    options: [
      { id: 'yes_regular', label: 'Yes, I drive regularly', shortTag: 'REGULAR DRIVER', cardLabel: 'Regular driver' },
      { id: 'yes_rarely', label: 'Yes, but I rarely drive', shortTag: 'LICENSED NON-DRIVER', cardLabel: 'Licensed but rarely drives' },
      { id: 'no_license', label: 'No driver’s license', shortTag: 'NO LICENSE', cardLabel: 'No driver’s license' },
    ],
  },
];

export const ALL_QUESTIONS: Question[] = [...CORE_QUESTIONS, ...BONUS_QUESTIONS];

export function getQuestionById(id: string): Question | undefined {
  return ALL_QUESTIONS.find((q) => q.id === id);
}
